import type { ReactNode } from "react";
import type { PdfV2Meta } from "./documentTypes";

export function PdfDocumentShell({ meta, children }: { meta: PdfV2Meta; children: ReactNode }) {
  const lang = meta.language || "ar";
  const dir = lang === "ar" ? "rtl" : "ltr";
  return (
    <div className="pdf-v2-doc" dir={dir} lang={lang}>
      <div className="pdf-v2-page">
        <header className="pdf-v2-header">
          <div className="pdf-v2-brand">
            <div className="pdf-v2-logo">AAED</div>
            <div>
              <div className="pdf-v2-company">{meta.companyName || "شركة الوفاء للأعمال المتكاملة"}</div>
              {(meta.companyDetails || []).map((line) => <div key={line} className="pdf-v2-company-line">{line}</div>)}
            </div>
          </div>
          <div className="pdf-v2-doc-meta">
            <div className="pdf-v2-doc-title">{meta.title || meta.documentType}</div>
            {meta.documentNumber && <div>{meta.documentNumber}</div>}
            {meta.documentDate && <div>{meta.documentDate}</div>}
          </div>
        </header>
        <main className="pdf-v2-content">{children}</main>
        <footer className="pdf-v2-footer">
          <span>{meta.footerNote || "Generated by AAED2"}</span>
          <span className="pdf-v2-page-number" />
        </footer>
      </div>
    </div>
  );
}
