import {useEffect,useMemo,useState} from "react";
import {Link,useParams,useSearchParams} from "react-router-dom";
import {useMutation,useQuery,useQueryClient} from "@tanstack/react-query";
import {useTranslation} from "react-i18next";
import {ArrowLeft,ArrowRight,BookOpen,Copy,FileDown,FileSpreadsheet,Printer,RefreshCw,Save,Search,X} from "lucide-react";
import {toast} from "sonner";
import {useAuth} from "@/contexts/AuthContext";
import {Button} from "@/components/ui/button";
import {Card,CardContent,CardHeader,CardTitle} from "@/components/ui/card";
import {Input} from "@/components/ui/input";
import {Checkbox} from "@/components/ui/checkbox";
import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from "@/components/ui/table";
import {formatOMR} from "@/lib/money";
import {exportReportRowsToPdf,exportReportRowsToXlsx,printReportRows,type ReportExportRequest} from "@/lib/reports-center/reportExportService";
import {
  ACCOUNTING_REPORTS,accountingReportColumns,accountingReportQueryKeys,fetchAccountingReport,
  fetchAllAccountingReportRows,listAccountingSavedViews,saveAccountingView,
  type AccountingReportDefinition,type AccountingReportFilters,type AccountingReportKey,type AccountingReportRow,
} from "@/lib/accounting/accountingReports";
import {hasAccountingPermission} from "@/lib/accounting/accountingAdministrationService";

const date=(delta=0)=>{const d=new Date();d.setMonth(d.getMonth()+delta);return d.toISOString().slice(0,10)};
function useEnglish(){const {i18n}=useTranslation();return i18n.resolvedLanguage?.startsWith("en")??false}
const labels:Record<string,{ar:string;en:string}>={entry_number:{ar:"رقم القيد",en:"Entry No."},date:{ar:"التاريخ",en:"Date"},account_code:{ar:"رمز الحساب",en:"Account Code"},name_ar:{ar:"اسم الحساب",en:"Account Name AR"},name_en:{ar:"الاسم الإنجليزي",en:"Account Name EN"},description:{ar:"الوصف",en:"Description"},debit:{ar:"مدين",en:"Debit"},credit:{ar:"دائن",en:"Credit"},balance:{ar:"الرصيد",en:"Balance"},revenue:{ar:"الإيراد",en:"Revenue"},cost:{ar:"التكلفة",en:"Cost"},profit:{ar:"الربح",en:"Profit"},status:{ar:"الحالة",en:"Status"},source_type:{ar:"المصدر",en:"Source"},reference:{ar:"المرجع",en:"Reference"},cost_center_code:{ar:"مركز التكلفة",en:"Cost Center"}};
const moneyKeys=new Set(["debit","credit","balance","revenue","cost","profit","subtotal","vat","total","paid","outstanding"]);
function label(key:string,en:boolean){return labels[key]?.[en?"en":"ar"]??key.replace(/_/g," ")}
function value(v:unknown,key:string,en:boolean){if(v===null||v===undefined||v==="")return "—";if(moneyKeys.has(key))return formatOMR(v);if(key.includes("date")){const d=new Date(String(v));if(!Number.isNaN(d.getTime()))return d.toLocaleDateString(en?"en-OM":"ar-OM")}return String(v)}

export function AccountingReportsCenterPage(){
  const en=useEnglish();
  return <main className="mx-auto max-w-7xl space-y-6 p-4 md:p-6">
    <header><h1 className="text-2xl font-bold">{en?"Accounting Reports":"تقارير المحاسبة"}</h1><p className="text-muted-foreground">{en?"Standalone, tenant-isolated reports based on posted journals.":"تقارير مستقلة ومعزولة حسب المؤسسة وتعتمد القيود المرحلة."}</p></header>
    <Card className="border-blue-300 bg-gradient-to-l from-blue-50 to-white dark:from-blue-950/40 dark:to-background">
      <CardHeader className="pb-2"><CardTitle className="flex items-center gap-2 text-lg"><BookOpen size={19}/>{en?"Comprehensive monthly workshop report":"التقرير الشهري الشامل للورشة"}</CardTitle></CardHeader>
      <CardContent><p className="mb-3 text-sm text-muted-foreground">{en?"A cloud monthly report separating cash and insurance, with vehicle profitability, payroll, operating expenses, and a workshop profit and loss summary.":"تقرير سحابي يفصل الكاش عن التأمين ويعرض ربحية كل سيارة والرواتب والمصروفات التشغيلية وملخص ربح وخسارة الورشة."}</p><Button asChild><Link to="/accounting/reports/monthly-vehicle-profitability">{en?"Open monthly report":"فتح التقرير الشهري"}</Link></Button></CardContent>
    </Card>
    <Card className="border-amber-300 bg-gradient-to-l from-amber-50 to-white dark:from-amber-950/30 dark:to-background">
      <CardHeader className="pb-2"><CardTitle className="flex items-center gap-2 text-lg"><FileSpreadsheet size={19}/>{en?"Monthly expense report":"تقرير المصروفات الشهرية"}</CardTitle></CardHeader>
      <CardContent><p className="mb-3 text-sm text-muted-foreground">{en?"Actual expense vouchers with automatic payroll and fixed-cost accruals, without double counting.":"سندات المصروف الفعلية مع سحب الرواتب والتكاليف الثابتة تلقائيًا ودون احتساب مزدوج."}</p><Button asChild><Link to="/accounting/reports/monthly-expenses">{en?"Open expense report":"فتح تقرير المصروفات"}</Link></Button></CardContent>
    </Card>
    <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{ACCOUNTING_REPORTS.map(r=><Card key={r.key}><CardHeader className="pb-2"><CardTitle className="flex items-center gap-2 text-base"><BookOpen size={17}/>{en?r.titleEn:r.titleAr}</CardTitle></CardHeader><CardContent><p className="mb-3 text-sm text-muted-foreground">{en?r.descriptionEn:r.descriptionAr}</p><Button asChild size="sm"><Link to={`/accounting/reports/${r.path}`}>{en?"Open report":"فتح التقرير"}</Link></Button></CardContent></Card>)}</div>
  </main>
}

function useFilters(def:AccountingReportDefinition,forced?:Partial<AccountingReportFilters>){
  const [params,setParams]=useSearchParams(); const [search,setSearch]=useState(params.get("search")??"");
  useEffect(()=>{const timer=setTimeout(()=>{if((params.get("search")??"")===search)return;const next=new URLSearchParams(params);if(search)next.set("search",search);else next.delete("search");next.set("page","1");setParams(next,{replace:true})},350);return()=>clearTimeout(timer)},[params,search,setParams]); // URL is the canonical filter state after debounce.
  const filters=useMemo<AccountingReportFilters>(()=>({from:params.get("from")??date(-1),to:params.get("to")??date(),page:Number(params.get("page")??1),pageSize:Number(params.get("pageSize")??50),search:params.get("search")??"",accountId:params.get("accountId")??undefined,costCenterId:params.get("costCenterId")??undefined,status:params.get("status")??undefined,businessType:params.get("businessType")??undefined,sort:params.get("sort")??"date",direction:(params.get("direction")==="asc"?"asc":"desc"),...forced}),[params,forced]);
  const set=(key:string,v:string)=>{const next=new URLSearchParams(params);if(v)next.set(key,v);else next.delete(key);if(key!=="page")next.set("page","1");setParams(next)};
  const clear=()=>{setSearch("");setParams({from:date(-1),to:date(),page:"1",pageSize:"50"})};
  const apply=(values:Record<string,unknown>)=>{const next=new URLSearchParams();Object.entries(values).forEach(([key,value])=>{if(value!==null&&value!==undefined&&value!=="")next.set(key,String(value))});setSearch(String(values.search??""));setParams(next,{replace:false})};
  return {filters,set,clear,apply,search,setSearch};
}

function ReportPage({definition,forced}:{definition:AccountingReportDefinition;forced?:Partial<AccountingReportFilters>}){
  const en=useEnglish();const {profile}=useAuth();const qc=useQueryClient();const state=useFilters(definition,forced);const [exporting,setExporting]=useState<string|null>(null);const [viewName,setViewName]=useState("");const [visible,setVisible]=useState<string[]>([]);
  const query=useQuery({queryKey:accountingReportQueryKeys.report(profile?.tenant_id,definition.key,state.filters),queryFn:({signal})=>fetchAccountingReport(definition.key,state.filters,signal),enabled:Boolean(profile?.tenant_id),staleTime:120_000,gcTime:900_000,refetchOnWindowFocus:false,placeholderData:p=>p});
  const saved=useQuery({queryKey:accountingReportQueryKeys.saved(profile?.tenant_id,definition.key),queryFn:()=>listAccountingSavedViews(definition.key),enabled:Boolean(profile?.tenant_id),staleTime:120_000,refetchOnWindowFocus:false});
  const save=useMutation({mutationFn:()=>saveAccountingView(profile!.tenant_id,profile!.user_id,definition.key,viewName,state.filters),onSuccess:()=>{toast.success(en?"View saved":"تم حفظ العرض");setViewName("");void qc.invalidateQueries({queryKey:accountingReportQueryKeys.saved(profile?.tenant_id,definition.key)})},onError:e=>toast.error(String((e as Error).message))});
  const rows=query.data?.rows??[];const columns=useMemo(()=>accountingReportColumns(rows),[rows]);useEffect(()=>{if(columns.length&&!visible.length)setVisible(columns)},[columns]);const shown=columns.filter(c=>visible.includes(c));
  const request=(all:AccountingReportRow[]):ReportExportRequest<AccountingReportRow>=>({fileName:`${definition.key}_${state.filters.from}_${state.filters.to}.xlsx`,sheetName:definition.key,title:en?definition.titleEn:definition.titleAr,filters:[{label:en?"From":"من",value:state.filters.from},{label:en?"To":"إلى",value:state.filters.to},...Object.entries(state.filters).filter(([k,v])=>!["from","to","page","pageSize"].includes(k)&&Boolean(v)).map(([k,v])=>({label:k,value:String(v)}) as {label:string;value:string})],columns:shown.map(k=>({key:k,label:label(k,en),type:moneyKeys.has(k)?"money":k.includes("date")?"date":"text"})),rows:all,language:en?"en":"ar",generatedBy:profile?.full_name||profile?.user_id||"Authenticated user",generatedAt:new Date().toISOString()});
  const runExport=async(kind:"xlsx"|"pdf"|"print")=>{setExporting(kind);try{const permission=kind==="xlsx"?"accounting_reports.export_excel":kind==="pdf"?"accounting_reports.export_pdf":"accounting_reports.print";if(!await hasAccountingPermission(permission))throw new Error(en?"You do not have permission for this export.":"لا تملك صلاحية إنشاء هذا المستخرج.");const all=await fetchAllAccountingReportRows(definition.key,state.filters);if(!all.length)throw new Error(en?"No rows to export":"لا توجد سجلات للتصدير");const req=request(all);if(kind==="xlsx")exportReportRowsToXlsx(req);else if(kind==="pdf")await exportReportRowsToPdf(req);else await printReportRows(req);toast.success(en?"Export completed":"تم إنشاء المستخرج")}catch(e){toast.error(String((e as Error).message))}finally{setExporting(null)}};
  const Back=en?ArrowLeft:ArrowRight;
  return <main className="mx-auto max-w-[1500px] space-y-4 p-4 md:p-6" dir={en?"ltr":"rtl"}>
    <header className="flex flex-col gap-3 border-b pb-4 lg:flex-row lg:items-start lg:justify-between"><div className="flex gap-3"><Button asChild variant="outline" size="icon"><Link to="/accounting/reports"><Back size={16}/></Link></Button><div><p className="text-xs text-muted-foreground">{en?"Accounting / Reports":"المحاسبة / التقارير"}</p><h1 className="text-2xl font-bold">{en?definition.titleEn:definition.titleAr}</h1><p className="text-sm text-muted-foreground">{en?definition.descriptionEn:definition.descriptionAr}</p></div></div><div className="flex flex-wrap gap-2"><Button variant="outline" onClick={()=>query.refetch()}><RefreshCw size={15}/>{en?"Refresh":"تحديث"}</Button><Button variant="outline" disabled={Boolean(exporting)} onClick={()=>void runExport("xlsx")}><FileSpreadsheet size={15}/>XLSX</Button><Button variant="outline" disabled={Boolean(exporting)} onClick={()=>void runExport("pdf")}><FileDown size={15}/>PDF</Button><Button variant="outline" disabled={Boolean(exporting)} onClick={()=>void runExport("print")}><Printer size={15}/>{en?"Print":"طباعة"}</Button></div></header>
    <Card><CardContent className="grid gap-3 pt-4 md:grid-cols-2 xl:grid-cols-6"><label className="text-sm">{en?"From":"من"}<Input type="date" value={state.filters.from} onChange={e=>state.set("from",e.target.value)}/></label><label className="text-sm">{en?"To":"إلى"}<Input type="date" value={state.filters.to} onChange={e=>state.set("to",e.target.value)}/></label><label className="text-sm xl:col-span-2">{en?"Search":"بحث"}<div className="relative"><Search className="absolute start-2 top-2.5" size={15}/><Input className="ps-8" value={state.search} onChange={e=>state.setSearch(e.target.value)}/></div></label><label className="text-sm">{en?"Business Type":"نوع العمل"}<select className="h-10 w-full rounded-md border bg-background px-2" value={state.filters.businessType??""} onChange={e=>state.set("businessType",e.target.value)}><option value="">{en?"All":"الكل"}</option><option value="insurance">Insurance</option><option value="cash">Cash</option></select></label><div className="flex items-end"><Button variant="ghost" onClick={state.clear}><X size={15}/>{en?"Clear all":"مسح الكل"}</Button></div></CardContent></Card>
    <div className="flex flex-wrap items-center gap-2 text-xs">{Object.entries(state.filters).filter(([k,v])=>!["page","pageSize"].includes(k)&&Boolean(v)).map(([k,v])=><span key={k} className="rounded-full border bg-muted px-2 py-1">{k}: {String(v)}</span>)}<Button variant="ghost" size="sm" onClick={()=>{void navigator.clipboard.writeText(location.href);toast.success(en?"Link copied":"\u062a\u0645 \u0646\u0633\u062e \u0627\u0644\u0631\u0627\u0628\u0637")}}><Copy size={14}/>{en?"Copy link":"\u0646\u0633\u062e \u0627\u0644\u0631\u0627\u0628\u0637"}</Button></div>
    <Card><CardContent className="flex flex-wrap gap-2 pt-4"><Input className="max-w-xs" placeholder={en?"Saved view name":"اسم العرض المحفوظ"} value={viewName} onChange={e=>setViewName(e.target.value)}/><Button disabled={!viewName.trim()||save.isPending} onClick={()=>save.mutate()}><Save size={15}/>{en?"Save view":"\u062d\u0641\u0638 \u0627\u0644\u0639\u0631\u0636"}</Button>{saved.data?.map(v=><Button key={v.id} variant="outline" onClick={()=>state.apply(v.filters)}>{v.name}</Button>)}</CardContent></Card>
    {query.data&&<><div className="grid grid-cols-2 gap-2 md:grid-cols-4">{Object.entries(query.data.aggregates).map(([k,v])=><Card key={k}><CardContent className="pt-4"><p className="text-xs text-muted-foreground">{label(k,en)}</p><p className="font-bold" dir="ltr">{moneyKeys.has(k)?formatOMR(v):Number(v).toLocaleString("en-US")}</p></CardContent></Card>)}</div><div className={`rounded-lg border p-3 text-sm ${query.data.dataQuality.status==="ready"?"border-emerald-300 bg-emerald-50":"border-amber-300 bg-amber-50"}`}>{en?"Accounting basis":"الأساس المحاسبي"}: <b>{query.data.basis}</b> — {en?"Eligibility applied":"تم تطبيق استبعاد السجلات غير المؤهلة"}: {query.data.dataQuality.excludedRecordsApplied?"Yes":"No"}</div></>}
    <Card><CardContent className="pt-4">{query.isLoading?<div className="p-12 text-center">{en?"Loading…":"جاري التحميل…"}</div>:query.isError?<div className="p-8 text-destructive">{String((query.error as Error).message)}</div>:!rows.length?<div className="p-12 text-center text-muted-foreground">{en?"No posted accounting data for these filters. Complete accounting readiness and post entries first.":"لا توجد بيانات محاسبية مرحلة لهذه الفلاتر. أكمل الجاهزية ورحّل القيود أولًا."}</div>:<><div className="mb-3 flex flex-wrap gap-3">{columns.map(c=><label key={c} className="flex items-center gap-1 text-xs"><Checkbox checked={visible.includes(c)} onCheckedChange={x=>setVisible(old=>x?[...new Set([...old,c])]:old.filter(v=>v!==c))}/>{label(c,en)}</label>)}</div><div className="overflow-x-auto"><Table className="min-w-[900px]"><TableHeader><TableRow>{shown.map(c=><TableHead key={c}>{label(c,en)}</TableHead>)}</TableRow></TableHeader><TableBody>{rows.map((row,i)=><TableRow key={String(row.id??i)}>{shown.map(c=><TableCell key={c} dir={moneyKeys.has(c)?"ltr":undefined}>{value(row[c],c,en)}</TableCell>)}</TableRow>)}</TableBody></Table></div><div className="mt-4 flex justify-between"><span>{en?"Rows":"السجلات"}: {query.data?.pagination.totalRows??0}</span><div className="flex gap-2"><Button variant="outline" disabled={state.filters.page<=1} onClick={()=>state.set("page",String(state.filters.page-1))}>{en?"Previous":"السابق"}</Button><span className="p-2" dir="ltr">{state.filters.page} / {query.data?.pagination.totalPages||1}</span><Button variant="outline" disabled={state.filters.page>=(query.data?.pagination.totalPages||1)} onClick={()=>state.set("page",String(state.filters.page+1))}>{en?"Next":"التالي"}</Button></div></div></>}</CardContent></Card>
    <Card><CardContent className="pt-4 text-sm text-muted-foreground">{en?"Calculation: posted journal lines only. Revenue uses credits net of debits; costs use debits net of credits. Deleted, cancelled, void, failed, reversed, archived and cross-tenant records are excluded at the database layer.":"طريقة الاحتساب: القيود المرحلة فقط. الإيراد دائن ناقص مدين، والتكاليف مدين ناقص دائن. يتم استبعاد المحذوف والملغى وVoid والفاشل والمعكوس والمؤرشف وسجلات Tenant آخر داخل قاعدة البيانات."}</CardContent></Card>
  </main>
}

export function AccountingReportPage({reportKey,forced}:{reportKey:AccountingReportKey;forced?:Partial<AccountingReportFilters>}){const def=ACCOUNTING_REPORTS.find(r=>r.key===reportKey);if(!def)return null;return <ReportPage definition={def} forced={forced}/>}
export function JournalEntryDetailPage(){const {entryId}=useParams();return <AccountingReportPage reportKey="journal" forced={{entryId}}/>}
export function GeneralLedgerAccountPage(){const {accountId}=useParams();return <AccountingReportPage reportKey="general-ledger" forced={{accountId}}/>}
export function VehicleProfitLossDetailPage(){const {operationId}=useParams();return <AccountingReportPage reportKey="vehicle-profit-loss" forced={{workOrderId:operationId}}/>}
