import * as XLSX from "xlsx";
import { formatOMR } from "@/lib/money";
import { exportReportToPdf, printReport } from "@/lib/reportExporters";

export interface ReportExportColumn<Row extends Record<string, unknown>> {
  key: keyof Row & string;
  label: string;
  type?: "text" | "money" | "date" | "number" | "percentage";
}

export interface ReportExportRequest<Row extends Record<string, unknown>> {
  fileName: string;
  sheetName: string;
  title: string;
  filters: Array<{ label: string; value: string }>;
  columns: ReportExportColumn<Row>[];
  rows: Row[];
  language?: "ar" | "en";
  generatedBy?: string;
  generatedAt?: string;
}

function cellValue<Row extends Record<string, unknown>>(row: Row, column: ReportExportColumn<Row>) {
  const value = row[column.key];
  if (column.type === "money") return Number(value || 0);
  if (column.type === "number" || column.type === "percentage") return Number(value || 0);
  if (column.type === "date" && value) {
    const date = new Date(String(value));
    if (!Number.isNaN(date.getTime())) return date.toISOString().slice(0, 10);
  }
  return value ?? "";
}

export function buildReportWorkbook<Row extends Record<string, unknown>>(
  request: ReportExportRequest<Row>,
) {
  if (!request.rows.length) throw new Error("The report contains no rows to export.");

  const headingRows: unknown[][] = [
    [request.title],
    ["Generated at", request.generatedAt || new Date().toISOString()],
    ["Generated by", request.generatedBy || "Authenticated user"],
    ...request.filters.map((filter) => [filter.label, filter.value]),
    [],
    request.columns.map((column) => column.label),
  ];
  const dataRows = request.rows.map((row) => request.columns.map((column) => cellValue(row, column)));
  const worksheet = XLSX.utils.aoa_to_sheet([...headingRows, ...dataRows]);
  const headerRow = headingRows.length;
  const lastRow = headerRow + dataRows.length;
  const lastColumn = Math.max(0, request.columns.length - 1);

  worksheet["!autofilter"] = { ref: XLSX.utils.encode_range({ r: headerRow - 1, c: 0 }, { r: lastRow - 1, c: lastColumn }) };
  worksheet["!freeze"] = { xSplit: 0, ySplit: headerRow } as any;
  worksheet["!cols"] = request.columns.map((column, columnIndex) => {
    const contentWidth = dataRows.reduce(
      (width, row) => Math.max(width, String(row[columnIndex] ?? "").length),
      0,
    );
    return { wch: Math.min(48, Math.max(14, column.label.length + 4, contentWidth + 2)) };
  });

  request.columns.forEach((column, columnIndex) => {
    if (column.type !== "money") return;
    for (let rowIndex = headerRow; rowIndex < lastRow; rowIndex += 1) {
      const address = XLSX.utils.encode_cell({ r: rowIndex, c: columnIndex });
      if (worksheet[address]) worksheet[address].z = '0.000 "OMR"';
    }
  });

  const workbook = XLSX.utils.book_new();
  const summary = XLSX.utils.aoa_to_sheet([
    [request.title],
    ["Generated at", request.generatedAt || new Date().toISOString()],
    ["Generated by", request.generatedBy || "Authenticated user"],
    ["Rows", request.rows.length],
    [],
    ["Filter", "Value"],
    ...request.filters.map((filter) => [filter.label, filter.value]),
  ]);
  summary["!cols"] = [{ wch: 24 }, { wch: 42 }];
  summary["!freeze"] = { xSplit: 0, ySplit: 6 } as any;
  summary["!autofilter"] = {
    ref: `A6:B${Math.max(6, 6 + request.filters.length)}`,
  };
  XLSX.utils.book_append_sheet(workbook, summary, "Summary");
  XLSX.utils.book_append_sheet(workbook, worksheet, request.sheetName.slice(0, 31));
  return workbook;
}

export function exportReportRowsToXlsx<Row extends Record<string, unknown>>(request: ReportExportRequest<Row>) {
  const workbook = buildReportWorkbook(request);
  XLSX.writeFile(workbook, request.fileName.endsWith(".xlsx") ? request.fileName : `${request.fileName}.xlsx`);
}

export function formatReportMoney(value: unknown): string {
  return formatOMR(value);
}

export function buildPrintableReportRequest<Row extends Record<string, unknown>>(
  request: ReportExportRequest<Row>,
) {
  return {
    title: request.title,
    subtitle: request.filters.map((filter) => `${filter.label}: ${filter.value}`).join(" | "),
    columns: request.columns.map((column) => ({
      key: column.key,
      label: column.label,
      align: column.type === "money" || column.type === "number" ? ("center" as const) : undefined,
      format:
        column.type === "money"
          ? (value: unknown) => formatOMR(value)
          : column.type === "percentage"
            ? (value: unknown) => `${Number(value || 0).toLocaleString("en-US", { maximumFractionDigits: 3 })}%`
            : undefined,
    })),
    rows: request.rows,
    language: request.language,
    generatedBy: request.generatedBy,
    generatedAt: request.generatedAt,
  };
}

export async function exportReportRowsToPdf<Row extends Record<string, unknown>>(
  request: ReportExportRequest<Row>,
) {
  if (!request.rows.length) throw new Error("The report contains no rows to export.");
  await exportReportToPdf(
    buildPrintableReportRequest(request),
    request.fileName.replace(/\.xlsx$/i, ".pdf"),
  );
}

export async function printReportRows<Row extends Record<string, unknown>>(
  request: ReportExportRequest<Row>,
) {
  if (!request.rows.length) throw new Error("The report contains no rows to print.");
  await printReport(buildPrintableReportRequest(request));
}
