import type { ReportDefinition } from "./reportTypes";

const commonPermissions = ["admin", "manager", "accountant"] as const;
const operationalPermissions = ["admin", "manager", "accountant", "insurance", "supervisor"] as const;

const moneyColumns = [
  { key: "invoiceSubtotal", label: { ar: "قبل الضريبة", en: "Subtotal" }, type: "money" as const },
  { key: "vat", label: { ar: "الضريبة", en: "VAT" }, type: "money" as const },
  { key: "invoiceTotal", label: { ar: "الإجمالي", en: "Invoice Total" }, type: "money" as const },
  { key: "paid", label: { ar: "المدفوع", en: "Paid" }, type: "money" as const },
  { key: "outstanding", label: { ar: "المتبقي", en: "Outstanding" }, type: "money" as const },
];

export const REPORT_DEFINITIONS: ReportDefinition[] = [
  {
    key: "claims-register",
    title: { ar: "سجل مطالبات التأمين", en: "Insurance Claims Register" },
    description: { ar: "المطالبات وحالاتها ومددها دون اعتبار التقدير إيرادًا.", en: "Claims, statuses and durations without recognizing estimates as revenue." },
    category: "insurance",
    businessTypes: ["insurance"],
    permissions: [...operationalPermissions],
    route: "/insurance/list",
    filters: ["date", "insuranceCompany", "claimStatus", "vehicle", "plate", "claimNumber"],
    columns: [
      { key: "claimNumber", label: { ar: "رقم المطالبة", en: "Claim Number" }, type: "text" },
      { key: "insuranceCompany", label: { ar: "شركة التأمين", en: "Insurance Company" }, type: "text" },
      { key: "vehicleName", label: { ar: "المركبة", en: "Vehicle" }, type: "text" },
      { key: "status", label: { ar: "الحالة", en: "Status" }, type: "status" },
      { key: "estimateAmount", label: { ar: "التقدير", en: "Estimate" }, type: "money" },
      { key: "approvedAmount", label: { ar: "المعتمد", en: "Approved" }, type: "money" },
    ],
    sorting: ["createdAt", "claimNumber", "status"],
    grouping: ["insuranceCompany", "status", "month"],
    totals: ["claimsCount", "estimateTotal", "approvedTotal"],
    exportFormats: ["screen", "pdf", "xlsx", "print"],
    calculationNotes: [
      { ar: "التقدير والمعتمد قيمتان معلوماتيتان وليستا إيرادًا.", en: "Estimate and approved amounts are informational, not revenue." },
    ],
    implementation: "ready",
  },
  {
    key: "insurance-company-statement",
    title: { ar: "كشف حساب شركة التأمين", en: "Insurance Company Statement" },
    description: { ar: "الفواتير والدفعات والرصيد لكل شركة تأمين.", en: "Invoices, payments and outstanding balance per insurance company." },
    category: "insurance",
    businessTypes: ["insurance"],
    permissions: [...commonPermissions, "insurance"],
    route: "/insurance/companies",
    filters: ["date", "insuranceCompany", "invoiceStatus", "collectionStatus"],
    columns: [
      { key: "invoiceNumber", label: { ar: "رقم الفاتورة", en: "Invoice Number" }, type: "text" },
      { key: "claimNumber", label: { ar: "رقم المطالبة", en: "Claim Number" }, type: "text" },
      ...moneyColumns,
    ],
    sorting: ["invoiceDate", "invoiceNumber", "outstanding"],
    grouping: ["insuranceCompany", "month", "collectionStatus"],
    totals: ["invoiceSubtotal", "vat", "invoiceTotal", "paid", "outstanding"],
    exportFormats: ["screen", "pdf", "xlsx", "print"],
    calculationNotes: [
      { ar: "المدفوع من الدفعات الفعلية المسجلة فقط.", en: "Paid amount comes from recorded successful payments only." },
    ],
    implementation: "ready",
  },
  {
    key: "cash-invoices",
    title: { ar: "فواتير الكاش والتحصيل", en: "Cash Invoices & Collections" },
    description: { ar: "فواتير العملاء غير المرتبطة بمطالبات التأمين.", en: "Customer invoices not linked to insurance claims." },
    category: "cash",
    businessTypes: ["cash"],
    permissions: [...commonPermissions],
    route: "/sales/invoices",
    filters: ["date", "customer", "vehicle", "invoiceStatus", "collectionStatus"],
    columns: [
      { key: "invoiceNumber", label: { ar: "رقم الفاتورة", en: "Invoice Number" }, type: "text" },
      { key: "customer", label: { ar: "العميل", en: "Customer" }, type: "text" },
      ...moneyColumns,
    ],
    sorting: ["invoiceDate", "invoiceNumber", "outstanding"],
    grouping: ["customer", "month", "collectionStatus"],
    totals: ["invoiceSubtotal", "vat", "invoiceTotal", "paid", "outstanding"],
    exportFormats: ["screen", "pdf", "xlsx", "print"],
    calculationNotes: [
      { ar: "تستبعد فواتير المسودة والملغاة.", en: "Draft and cancelled invoices are excluded." },
    ],
    implementation: "ready",
  },
  {
    key: "all-company-invoices",
    title: { ar: "كل فواتير الشركة", en: "All Company Invoices" },
    description: { ar: "عرض موحد مع عمود نوع العمل دون خلط مصادر التأمين والكاش.", en: "Combined view with business type while preserving separate sources." },
    category: "combined",
    businessTypes: ["all", "insurance", "cash"],
    permissions: [...commonPermissions],
    route: "/reports/cloud-advanced",
    filters: ["businessType", "date", "invoiceNumber", "invoiceStatus", "collectionStatus"],
    columns: [
      { key: "businessType", label: { ar: "نوع العمل", en: "Business Type" }, type: "status" },
      { key: "invoiceNumber", label: { ar: "رقم الفاتورة", en: "Invoice Number" }, type: "text" },
      ...moneyColumns,
    ],
    sorting: ["invoiceDate", "invoiceNumber", "outstanding"],
    grouping: ["businessType", "month", "collectionStatus"],
    totals: ["invoiceSubtotal", "vat", "invoiceTotal", "paid", "outstanding"],
    exportFormats: ["screen", "pdf", "xlsx", "print"],
    calculationNotes: [
      { ar: "مصدر التأمين insurance_invoices ومصدر الكاش sales_documents.", en: "Insurance uses insurance_invoices; cash uses sales_documents." },
    ],
    implementation: "ready",
  },
  {
    key: "work-orders",
    title: { ar: "تقرير أوامر العمل", en: "Work Orders Report" },
    description: { ar: "الحالة والنوع والمركبة والمدة والفاتورة المرتبطة.", en: "Status, type, vehicle, duration and linked invoice." },
    category: "operations",
    businessTypes: ["all", "insurance", "cash"],
    permissions: [...operationalPermissions],
    route: "/reports/work-orders-statement",
    filters: ["businessType", "date", "workOrderStatus", "vehicle", "employee"],
    columns: [
      { key: "workOrderNumber", label: { ar: "أمر العمل", en: "Work Order" }, type: "text" },
      { key: "businessType", label: { ar: "نوع العمل", en: "Business Type" }, type: "status" },
      { key: "status", label: { ar: "الحالة", en: "Status" }, type: "status" },
      { key: "workshopDays", label: { ar: "أيام الورشة", en: "Workshop Days" }, type: "number" },
    ],
    sorting: ["createdAt", "workOrderNumber", "status"],
    grouping: ["businessType", "status", "technician"],
    totals: ["workOrdersCount", "averageWorkshopDays"],
    exportFormats: ["screen", "pdf", "xlsx", "print"],
    calculationNotes: [
      { ar: "أمر العمل بلا فاتورة لا يولّد إيرادًا.", en: "A work order without an invoice does not generate revenue." },
    ],
    implementation: "ready",
  },
  {
    key: "vehicles-in-workshop",
    title: { ar: "المركبات داخل الورشة", en: "Vehicles in Workshop" },
    description: { ar: "المركبات النشطة ومواقعها ومدة بقائها.", en: "Active vehicles, locations and stay duration." },
    category: "operations",
    businessTypes: ["all", "insurance", "cash"],
    permissions: [...operationalPermissions],
    route: "/work-orders",
    filters: ["businessType", "vehicleStatus", "workshopLocation", "plate"],
    columns: [
      { key: "plate", label: { ar: "اللوحة", en: "Plate" }, type: "text" },
      { key: "vehicleName", label: { ar: "المركبة", en: "Vehicle" }, type: "text" },
      { key: "status", label: { ar: "الحالة", en: "Status" }, type: "status" },
      { key: "workshopDays", label: { ar: "الأيام", en: "Days" }, type: "number" },
    ],
    sorting: ["days", "plate"],
    grouping: ["businessType", "location", "status"],
    totals: ["vehiclesInWorkshop", "averageWorkshopDays"],
    exportFormats: ["screen", "pdf", "xlsx", "print"],
    calculationNotes: [],
    implementation: "ready",
  },
  {
    key: "completed-without-invoice",
    title: { ar: "مكتملة دون فاتورة", en: "Completed Without Invoice" },
    description: { ar: "أعمال مكتملة لا توجد لها فاتورة نهائية.", en: "Completed work with no final invoice." },
    category: "invoices",
    businessTypes: ["all", "insurance", "cash"],
    permissions: [...commonPermissions, "insurance"],
    route: "/reports/completed-without-invoice",
    filters: ["businessType", "date", "insuranceCompany", "customer"],
    columns: [
      { key: "reference", label: { ar: "المرجع", en: "Reference" }, type: "text" },
      { key: "reportDate", label: { ar: "تاريخ الإنجاز", en: "Completed At" }, type: "date" },
      { key: "businessType", label: { ar: "نوع العمل", en: "Business Type" }, type: "status" },
    ],
    sorting: ["completedAt", "reference"],
    grouping: ["businessType", "month"],
    totals: ["completedWithoutInvoice"],
    exportFormats: ["screen", "pdf", "xlsx", "print"],
    calculationNotes: [
      { ar: "لا تُعرض هذه الأعمال كإيراد.", en: "These records are not recognized as revenue." },
    ],
    implementation: "ready",
  },
  {
    key: "delivered-awaiting-collection",
    title: { ar: "مسلّمة وبانتظار التحصيل", en: "Delivered Awaiting Collection" },
    description: { ar: "مركبات مسلمة لها فاتورة ورصيد متبقٍ.", en: "Delivered vehicles with an invoice and outstanding balance." },
    category: "invoices",
    businessTypes: ["all", "insurance", "cash"],
    permissions: [...commonPermissions, "insurance"],
    route: "/reports/overdue-invoices",
    filters: ["businessType", "date", "collectionStatus", "insuranceCompany", "customer"],
    columns: [
      { key: "invoiceNumber", label: { ar: "الفاتورة", en: "Invoice" }, type: "text" },
      { key: "deliveredAt", label: { ar: "التسليم", en: "Delivered At" }, type: "date" },
      ...moneyColumns,
    ],
    sorting: ["outstanding", "deliveredAt"],
    grouping: ["businessType", "collectionStatus"],
    totals: ["invoiceTotal", "paid", "outstanding"],
    exportFormats: ["screen", "pdf", "xlsx", "print"],
    calculationNotes: [],
    implementation: "ready",
  },
  {
    key: "expenses",
    title: { ar: "المصروفات والتكاليف الفعلية", en: "Actual Expenses & Costs" },
    description: { ar: "المصروفات الفعلية المصنفة دون التكاليف التقديرية.", en: "Classified actual expenses excluding estimated costs." },
    category: "expenses",
    businessTypes: ["all", "insurance", "cash"],
    permissions: [...commonPermissions],
    route: "/accounting/expenses",
    filters: ["businessType", "date", "supplier", "expenseCategory", "paymentMethod", "vehicle"],
    columns: [
      { key: "reference", label: { ar: "رقم السند", en: "Voucher Number" }, type: "text" },
      { key: "status", label: { ar: "التصنيف", en: "Category" }, type: "text" },
      { key: "invoiceSubtotal", label: { ar: "قبل الضريبة", en: "Subtotal" }, type: "money" },
      { key: "vat", label: { ar: "الضريبة", en: "VAT" }, type: "money" },
      { key: "invoiceTotal", label: { ar: "الإجمالي", en: "Total" }, type: "money" },
    ],
    sorting: ["date", "voucherNumber", "subtotal"],
    grouping: ["businessType", "category", "supplier", "month"],
    totals: ["expenses", "partsCost", "laborCost", "transportCost"],
    exportFormats: ["screen", "pdf", "xlsx", "print"],
    calculationNotes: [
      { ar: "تعتمد التكلفة على السندات والمشتريات الفعلية فقط.", en: "Costs come from actual expense and purchase records only." },
    ],
    implementation: "ready",
  },
  {
    key: "gross-profitability",
    title: { ar: "الربحية الإجمالية", en: "Gross Profitability" },
    description: { ar: "إيراد الفواتير قبل الضريبة ناقص التكاليف المباشرة الفعلية.", en: "Invoice subtotal minus actual direct costs." },
    category: "profitability",
    businessTypes: ["all", "insurance", "cash"],
    permissions: [...commonPermissions],
    route: "/reports/cloud-advanced",
    filters: ["businessType", "date", "vehicle", "customer", "insuranceCompany"],
    columns: [
      { key: "invoiceSubtotal", label: { ar: "إيراد قبل الضريبة", en: "Revenue Ex VAT" }, type: "money" },
      { key: "actualCost", label: { ar: "التكاليف المباشرة", en: "Direct Costs" }, type: "money" },
      { key: "grossProfit", label: { ar: "الربح الإجمالي", en: "Gross Profit" }, type: "money" },
    ],
    sorting: ["grossProfit", "grossMargin"],
    grouping: ["businessType", "vehicle", "month"],
    totals: ["invoiceSubtotal", "expenses", "grossProfit", "grossMargin"],
    exportFormats: ["screen", "pdf", "xlsx", "print"],
    calculationNotes: [
      { ar: "VAT خارج الربح. لا يُستخدم مصطلح صافي الربح هنا.", en: "VAT is excluded. This report does not claim net profit." },
    ],
    implementation: "ready",
  },
  {
    key: "workshop-duration",
    title: { ar: "الأداء ومدد الورشة", en: "Performance & Workshop Duration" },
    description: { ar: "متوسط زمن الوصول والبدء والإنجاز والتسليم.", en: "Average arrival, start, completion and delivery durations." },
    category: "performance",
    businessTypes: ["all", "insurance", "cash"],
    permissions: [...operationalPermissions],
    route: "/reports/vehicles-over-30-days",
    filters: ["businessType", "date", "employee", "insuranceCompany", "workOrderStatus"],
    columns: [
      { key: "reference", label: { ar: "المرجع", en: "Reference" }, type: "text" },
      { key: "reportDate", label: { ar: "التاريخ", en: "Date" }, type: "date" },
      { key: "workshopDays", label: { ar: "أيام الورشة", en: "Workshop Days" }, type: "number" },
    ],
    sorting: ["workshopDays", "arrivalAt"],
    grouping: ["businessType", "status", "insuranceCompany"],
    totals: ["averageWorkshopDays", "vehiclesInWorkshop"],
    exportFormats: ["screen", "pdf", "xlsx", "print"],
    calculationNotes: [],
    implementation: "ready",
  },
  {
    key: "payments",
    title: { ar: "سجل الدفعات الفعلية", en: "Recorded Payments" },
    description: { ar: "سندات القبض المسجلة مع فصل التأمين والكاش.", en: "Recorded receipts with insurance and cash kept structurally separated." },
    category: "invoices",
    businessTypes: ["all", "insurance", "cash"],
    permissions: [...commonPermissions],
    route: "/accounting/receipts",
    filters: ["businessType", "date", "customer", "insuranceCompany", "paymentMethod"],
    columns: [
      { key: "reference", label: { ar: "رقم السند", en: "Payment Number" }, type: "text" },
      { key: "reportDate", label: { ar: "التاريخ", en: "Date" }, type: "date" },
      { key: "businessType", label: { ar: "نوع العمل", en: "Business Type" }, type: "status" },
      { key: "partyName", label: { ar: "الجهة", en: "Party" }, type: "text" },
      { key: "paid", label: { ar: "المبلغ", en: "Amount" }, type: "money" },
      { key: "status", label: { ar: "الحالة", en: "Status" }, type: "status" },
    ],
    sorting: ["reportDate", "reference", "paid"],
    grouping: ["businessType", "month", "paymentMethod"],
    totals: ["paid"],
    exportFormats: ["screen", "pdf", "xlsx", "print"],
    calculationNotes: [
      { ar: "التحصيل من السندات الفعلية فقط.", en: "Collections come from recorded payments only." },
    ],
    implementation: "ready",
  },
  {
    key: "aging",
    title: { ar: "تعمير الذمم", en: "Receivables Aging" },
    description: { ar: "الأرصدة غير المحصلة موزعة حسب عمر الاستحقاق.", en: "Outstanding invoice balances grouped by due-date age." },
    category: "invoices",
    businessTypes: ["all", "insurance", "cash"],
    permissions: [...commonPermissions],
    route: "/reports/overdue-invoices",
    filters: ["businessType", "date", "customer", "insuranceCompany", "collectionStatus"],
    columns: [
      { key: "reference", label: { ar: "رقم الفاتورة", en: "Invoice Number" }, type: "text" },
      { key: "dueDate", label: { ar: "الاستحقاق", en: "Due Date" }, type: "date" },
      { key: "partyName", label: { ar: "الجهة", en: "Party" }, type: "text" },
      { key: "status", label: { ar: "فئة العمر", en: "Age Bucket" }, type: "status" },
      { key: "invoiceTotal", label: { ar: "الإجمالي", en: "Invoice Total" }, type: "money" },
      { key: "paid", label: { ar: "المدفوع", en: "Paid" }, type: "money" },
      { key: "outstanding", label: { ar: "المتبقي", en: "Outstanding" }, type: "money" },
    ],
    sorting: ["outstanding", "reportDate", "reference"],
    grouping: ["businessType", "status"],
    totals: ["invoiceTotal", "paid", "outstanding"],
    exportFormats: ["screen", "pdf", "xlsx", "print"],
    calculationNotes: [],
    implementation: "ready",
  },
];

export const REPORT_CATEGORIES = [
  { key: "overview", ar: "نظرة عامة", en: "Overview" },
  { key: "insurance", ar: "التأمين", en: "Insurance" },
  { key: "cash", ar: "الكاش", en: "Cash" },
  { key: "combined", ar: "موحدة", en: "Combined" },
  { key: "operations", ar: "التشغيل", en: "Operations" },
  { key: "invoices", ar: "الفواتير والتحصيل", en: "Invoices & Collections" },
  { key: "expenses", ar: "المصروفات والتكاليف", en: "Expenses & Costs" },
  { key: "profitability", ar: "الربحية", en: "Profitability" },
  { key: "performance", ar: "الأداء والمدد", en: "Performance & Duration" },
  { key: "saved", ar: "التقارير المحفوظة", en: "Saved Reports" },
] as const;
