import { FormEvent, useEffect, useMemo, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Link, useNavigate, useParams, useSearchParams } from "react-router-dom";
import { Loader2, Search } from "lucide-react";
import { useTranslation } from "react-i18next";
import { toast } from "sonner";
import { useAuth } from "@/contexts/AuthContext";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { queryKeys } from "@/lib/queryKeys";
import { calculateVatExclusive, roundMoney } from "@/lib/money";
import { getExpense, listCostCenters, listExpenseCategories, saveExpense, searchExpenseWorkOrders, searchSuppliers, setExpenseAttachments, uploadExpenseAttachment } from "@/lib/expenses/expenseClassificationService";

const today=()=>new Date().toISOString().slice(0,10);
const empty:any={date:today(),expense_scope:"work_order",work_order_id:"",linked_work_order_id:"",department_id:"",expense_category_id:"",subcategory_id:"",cost_center_id:"",supplier_id:"",supplier_invoice_number:"",payment_method:"cash",description:"",notes:"",reference_number:"",subtotal:"",vat:true,attachments:[]};
export default function ExpenseFormPage(){
 const {i18n}=useTranslation(); const isAr=i18n.language?.startsWith('ar');
 const {expenseId}=useParams(); const editing=!!expenseId; const [params]=useSearchParams(); const {profile,user}=useAuth(); const tenantId=profile?.tenant_id||""; const nav=useNavigate(); const qc=useQueryClient();
 const [form,setForm]=useState({...empty,work_order_id:params.get('work_order_id')||""}); const [woSearch,setWoSearch]=useState(""); const [supplierSearch,setSupplierSearch]=useState(""); const [file,setFile]=useState<File|null>(null);
 const [debouncedWo,setDebouncedWo]=useState(""); const [debouncedSupplier,setDebouncedSupplier]=useState("");
 useEffect(()=>{const t=setTimeout(()=>setDebouncedWo(woSearch),300);return()=>clearTimeout(t)},[woSearch]); useEffect(()=>{const t=setTimeout(()=>setDebouncedSupplier(supplierSearch),300);return()=>clearTimeout(t)},[supplierSearch]);
 const categories=useQuery({queryKey:queryKeys.expenseManagement.categories({tenantId,active:true}),enabled:!!tenantId,queryFn:()=>listExpenseCategories(tenantId,false)});
 const detail=useQuery({queryKey:queryKeys.expenseManagement.detail(expenseId),enabled:!!tenantId&&editing,queryFn:()=>getExpense(tenantId,expenseId!)});
 const workOrders=useQuery({queryKey:queryKeys.expenseManagement.workOrders(debouncedWo),enabled:debouncedWo.trim().length>=2,queryFn:()=>searchExpenseWorkOrders(debouncedWo)});
 const suppliers=useQuery({queryKey:queryKeys.expenseManagement.suppliers(debouncedSupplier),enabled:!!tenantId&&debouncedSupplier.trim().length>=2,queryFn:()=>searchSuppliers(tenantId,debouncedSupplier)});
 const centers=useQuery({queryKey:queryKeys.expenseManagement.costCenters,enabled:!!tenantId,queryFn:()=>listCostCenters(tenantId)});
 useEffect(()=>{if(detail.data){const d:any=detail.data;setForm({...empty,...d,subtotal:String(d.subtotal??d.amount??""),vat:Number(d.vat_amount||0)>0,work_order_id:d.work_order_id||"",attachments:d.attachments||[]})}},[detail.data]);
 const roots=useMemo(()=> (categories.data||[]).filter(c=>c.level===1&&(c.expense_scope===form.expense_scope||c.expense_scope==='both')),[categories.data,form.expense_scope]);
 const children=useMemo(()=> (categories.data||[]).filter(c=>c.parent_id===form.department_id&&(c.expense_scope===form.expense_scope||c.expense_scope==='both')),[categories.data,form.department_id,form.expense_scope]);
 const subs=useMemo(()=> (categories.data||[]).filter(c=>c.parent_id===form.expense_category_id),[categories.data,form.expense_category_id]);
 const totals=useMemo(()=>form.vat?calculateVatExclusive(form.subtotal):{subtotalBeforeVat:roundMoney(form.subtotal),vatAmount:0,totalIncludingVat:roundMoney(form.subtotal)},[form.subtotal,form.vat]);
 const save=useMutation({mutationFn:async()=>{const saved=await saveExpense({tenant_id:tenantId,date:form.date,expense_scope:form.expense_scope,work_order_id:form.expense_scope==='work_order'?form.work_order_id:null,linked_work_order_id:form.expense_scope==='work_order'?form.linked_work_order_id:null,department_id:form.department_id,expense_category_id:form.expense_category_id,subcategory_id:form.subcategory_id||null,cost_center_id:form.cost_center_id||null,supplier_id:form.supplier_id||null,supplier_invoice_number:form.supplier_invoice_number||null,payment_method:form.payment_method,description:form.description,notes:form.notes||null,reference_number:form.reference_number||null,subtotal:totals.subtotalBeforeVat,vat_amount:totals.vatAmount,total:totals.totalIncludingVat,is_vat_applicable:form.vat,attachments:form.attachments||[]},user?.id||"",expenseId);if(file){const uploaded=await uploadExpenseAttachment(tenantId,saved.id,file);await setExpenseAttachments(tenantId,saved.id,[...(saved.attachments||[]),uploaded])}return saved},onSuccess:()=>{toast.success("تم حفظ المصروف في Supabase");void qc.invalidateQueries({queryKey:queryKeys.expenseManagement.all});nav('/accounting/expenses')},onError:(e:Error)=>toast.error(e.message)});
 const submit=(e:FormEvent)=>{e.preventDefault();if(!tenantId||!form.department_id||!form.expense_category_id||!form.description.trim()||!totals.subtotalBeforeVat){toast.error('أكمل الحقول المطلوبة');return}if(form.expense_scope==='work_order'&&!form.work_order_id){toast.error('اختر أمر العمل');return}save.mutate()};
 const pickWo=(w:any)=>{setForm({...form,work_order_id:w.id,linked_work_order_id:w.order_number});setWoSearch(`${w.order_number} — ${w.plate||''}`)};
 return <div className="mx-auto max-w-5xl space-y-5 p-4 md:p-6" dir={isAr?'rtl':'ltr'}><div><h1 className="text-2xl font-bold">{editing?'تعديل المصروف':'إضافة مصروف'}</h1><p className="text-sm text-muted-foreground">Full-page entry — الربط والتصنيف يُتحقق منهما داخل قاعدة البيانات</p></div><form onSubmit={submit} className="space-y-4"><Card><CardHeader><CardTitle>نوع المصروف والربط</CardTitle></CardHeader><CardContent className="grid gap-4 md:grid-cols-2">
 <div><Label>النطاق</Label><Select value={form.expense_scope} onValueChange={v=>setForm({...form,expense_scope:v,work_order_id:"",linked_work_order_id:"",department_id:"",expense_category_id:"",subcategory_id:""})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="work_order">مصروف أمر عمل</SelectItem><SelectItem value="operating">مصروف تشغيلي</SelectItem></SelectContent></Select></div><div><Label>التاريخ</Label><Input type="date" value={form.date} onChange={e=>setForm({...form,date:e.target.value})}/></div>
 {form.expense_scope==='work_order'&&<div className="relative md:col-span-2"><Label>بحث أمر العمل (حرفان على الأقل)</Label><div className="flex gap-2"><Input value={woSearch} onChange={e=>setWoSearch(e.target.value)} placeholder="رقم الأمر، اللوحة، العميل أو المطالبة"/><Search className="mt-2 h-4 w-4"/></div>{workOrders.isFetching&&<Loader2 className="mt-2 h-4 w-4 animate-spin"/>}{(workOrders.data||[]).length>0&&<div className="mt-1 max-h-48 overflow-auto rounded border bg-background p-1">{workOrders.data!.map((w:any)=><button type="button" className="block w-full rounded p-2 text-start hover:bg-muted" key={w.id} onClick={()=>pickWo(w)}>{w.order_number} — {w.plate} {w.plate_letters} — {w.customer_name} ({w.channel})</button>)}</div>}<p className="mt-1 text-xs text-muted-foreground">المحدد: {form.linked_work_order_id||'لا يوجد'} — القناة والعميل والمركبة والمطالبة تُشتق من أمر العمل ولا تُدخل يدويًا.</p></div>}
 </CardContent></Card><Card><CardHeader><CardTitle>التصنيف المحاسبي</CardTitle></CardHeader><CardContent className="grid gap-4 md:grid-cols-3">
 <div><Label>القسم</Label><Select value={form.department_id||"none"} onValueChange={v=>setForm({...form,department_id:v,expense_category_id:"",subcategory_id:""})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{roots.map(c=><SelectItem value={c.id} key={c.id}>{c.name_ar} / {c.name_en}</SelectItem>)}</SelectContent></Select></div>
 <div><Label>التصنيف</Label><Select value={form.expense_category_id||"none"} onValueChange={v=>setForm({...form,expense_category_id:v,subcategory_id:""})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{children.map(c=><SelectItem value={c.id} key={c.id}>{c.name_ar} / {c.name_en}</SelectItem>)}</SelectContent></Select></div>
 <div><Label>التصنيف الفرعي</Label><Select value={form.subcategory_id||"none"} onValueChange={v=>setForm({...form,subcategory_id:v==='none'?'':v})}><SelectTrigger><SelectValue placeholder="اختياري"/></SelectTrigger><SelectContent><SelectItem value="none">بدون</SelectItem>{subs.map(c=><SelectItem value={c.id} key={c.id}>{c.name_ar} / {c.name_en}</SelectItem>)}</SelectContent></Select></div>
 <div><Label>مركز التكلفة</Label><Select value={form.cost_center_id||"none"} onValueChange={v=>setForm({...form,cost_center_id:v==='none'?'':v})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="none">تلقائي/غير محدد</SelectItem>{(centers.data||[]).map((c:any)=><SelectItem value={c.id} key={c.id}>{c.code} — {c.name_ar||c.name_en}</SelectItem>)}</SelectContent></Select></div>
 <div className="md:col-span-2"><Label>المورد (بحث عند الحاجة)</Label><Input value={supplierSearch} onChange={e=>setSupplierSearch(e.target.value)} placeholder="الاسم أو الهاتف أو الرقم الضريبي"/>{(suppliers.data||[]).length>0&&<div className="mt-1 max-h-32 overflow-auto rounded border">{suppliers.data!.map((s:any)=><button type="button" className="block w-full p-2 text-start hover:bg-muted" key={s.id} onClick={()=>{setForm({...form,supplier_id:s.id});setSupplierSearch(s.name)}}>{s.name} — {s.phone||''}</button>)}</div>}</div>
 </CardContent></Card><Card><CardHeader><CardTitle>المبلغ والمستند</CardTitle></CardHeader><CardContent className="grid gap-4 md:grid-cols-3">
 <div><Label>المبلغ قبل الضريبة OMR</Label><Input inputMode="decimal" value={form.subtotal} onChange={e=>setForm({...form,subtotal:e.target.value})}/></div><div><Label>VAT</Label><Select value={form.vat?'yes':'no'} onValueChange={v=>setForm({...form,vat:v==='yes'})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="yes">5%</SelectItem><SelectItem value="no">بدون VAT</SelectItem></SelectContent></Select></div><div className="rounded border p-3 text-sm"><div>Subtotal: {totals.subtotalBeforeVat.toFixed(3)}</div><div>VAT: {totals.vatAmount.toFixed(3)}</div><strong>Total: {totals.totalIncludingVat.toFixed(3)} OMR</strong></div>
 <div><Label>طريقة الدفع</Label><Select value={form.payment_method} onValueChange={v=>setForm({...form,payment_method:v})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="cash">Cash</SelectItem><SelectItem value="bank">Bank</SelectItem><SelectItem value="card">Card</SelectItem><SelectItem value="credit">Credit</SelectItem></SelectContent></Select></div><div><Label>رقم فاتورة المورد</Label><Input value={form.supplier_invoice_number} onChange={e=>setForm({...form,supplier_invoice_number:e.target.value})}/></div><div><Label>المرجع</Label><Input value={form.reference_number} onChange={e=>setForm({...form,reference_number:e.target.value})}/></div>
 <div className="md:col-span-3"><Label>البيان</Label><Textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></div><div className="md:col-span-2"><Label>ملاحظات</Label><Textarea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></div><div><Label>مرفق PDF/صورة (12MB)</Label><Input type="file" accept="application/pdf,image/jpeg,image/png,image/webp" onChange={e=>setFile(e.target.files?.[0]||null)}/></div>
 <div className="flex gap-2 md:col-span-3"><Button type="submit" disabled={save.isPending}>{save.isPending?'جاري الحفظ...':'حفظ المصروف'}</Button><Button variant="outline" asChild><Link to="/accounting/expenses">إلغاء</Link></Button></div>
 </CardContent></Card></form></div>;
}
